apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: eval-pipeline
  namespace: default
spec:
  params:
    - name: traceparent
      type: string
      default: ""
  tasks:
    - name: step-one
      taskRef:
        name: call-eval-backend
      params:
        - name: message
          value: "step-one"
        - name: traceparent
          value: "$(params.traceparent)"
    - name: step-two
      runAfter:
        - step-one
      taskRef:
        name: call-eval-backend
      params:
        - name: message
          value: "step-two"
        - name: traceparent
          value: "$(params.traceparent)"
    - name: step-three
      runAfter:
        - step-two
      taskRef:
        name: call-eval-backend
      params:
        - name: message
          value: "step-three"
        - name: traceparent
          value: "$(params.traceparent)"
