apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  namespace: tekton-pipelines
data:
  metrics-protocol: http/protobuf
  metrics-endpoint: "http://otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
  metrics-export-interval: "15s"
  tracing-protocol: http/protobuf
  tracing-endpoint: "http://otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
  tracing-sampling-rate: "1.0"
  metrics.taskrun.level: "task"
  metrics.taskrun.duration-type: "histogram"
  metrics.pipelinerun.level: "pipeline"
  metrics.pipelinerun.duration-type: "histogram"
  metrics.count.enable-reason: "false"
